<a href="https://colab.research.google.com/github/ayush24578/ayush24578-Concepts-and-Technologies-of-AI/blob/main/Ayush_Dhungana_Worksheet1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive

In [2]:
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
import numpy as np
empty_array=np.empty((2, 2))
print("Empty Array:", empty_array)


Empty Array: [[4.55496435e-315 0.00000000e+000]
 [2.66273468e-258 6.57447613e-085]]


In [4]:
ones_array=np.ones((4, 2))
print("All Ones Array:", ones_array)

All Ones Array: [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [5]:
filled_array = np.full((3, 3), fill_value=7, dtype=int)
print("\nFilled Array:\n", filled_array)


Filled Array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [6]:
sample_array=np.array([[5, 6, 7], [8, 9, 10]])
zeros_like_array=np.zeros_like(sample_array)
print("Zeros Like Array:", zeros_like_array)

Zeros Like Array: [[0 0 0]
 [0 0 0]]


In [7]:
ones_like_array=np.ones_like(sample_array)
print("Ones Like Array:", ones_like_array)

Ones Like Array: [[1 1 1]
 [1 1 1]]


In [8]:
new_list=[1, 2, 3, 4]
array_from_list=np.array(new_list)
print("Array from List:", array_from_list)

Array from List: [1 2 3 4]


In [9]:
arr=np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [10]:
matrix_3x3=np.arange(9).reshape(3, 3)
print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
rand_arr=np.random.random(30)
print(rand_arr)
print("Mean:", rand_arr.mean())

[0.76175595 0.34402743 0.25498109 0.26180786 0.26719622 0.17066577
 0.99957794 0.8774319  0.3663441  0.11809192 0.88608316 0.91356051
 0.45890675 0.8334511  0.53204643 0.19254941 0.15755701 0.27730064
 0.8164364  0.63386562 0.78271393 0.42796587 0.75455924 0.69891498
 0.66224609 0.30758368 0.6970979  0.82239963 0.11413897 0.21711217]
Mean: 0.5202789893792172


In [13]:
rand_10x10=np.random.random((10, 10))
print("Min:", rand_10x10.min())
print("Max:", rand_10x10.max())

Min: 0.015179898613778331
Max: 0.9827946500366749


In [14]:
zero_arr=np.zeros(10)
zero_arr[4]=1
print(zero_arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [15]:
arr=np.array([1, 2, 0, 0, 4, 0])
reversed_arr=arr[::-1]
print(reversed_arr)

[0 4 0 0 2 1]


In [16]:
border_arr=np.ones((5, 5))
border_arr[1:-1, 1:-1] = 0
print(border_arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [17]:
checkerboard=np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2]=1
checkerboard[::2, 1::2]=1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [18]:
import numpy as np

x = np.array([[1, 2],
              [3, 5]])

y = np.array([[5, 6],
              [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

add_xy = x + y
print(add_xy)

sub_xy = x - y
print(sub_xy)

mul_x = x * 3
print(mul_x)

square_x = x ** 2
print(square_x)

dot_vw = np.dot(v, w)
print(dot_vw)

dot_xv = np.dot(x, v)
print(dot_xv)

dot_xy = np.dot(x, y)
print(dot_xy)

concat_xy = np.concatenate((x, y), axis=0)
print(concat_xy)

concat_vw = np.column_stack((v, w))
print(concat_vw)


[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[ 3  6]
 [ 9 15]]
[[ 1  4]
 [ 9 25]]
219
[29 77]
[[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]


In [19]:
np.concatenate((x, v))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [20]:
A = np.array([[3, 4],
              [7, 8]])

B = np.array([[5, 3],
              [2, 1]])

A_inv = np.linalg.inv(A)
result = A.dot(A_inv)
print(result)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [21]:
AB = A.dot(B)
BA = B.dot(A)

print("AB =\n", AB)
print("BA =\n", BA)

AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]


In [22]:
left_side = (A.dot(B)).T
right_side = B.T.dot(A.T)

print("Left Side (AB)^T =\n", left_side)
print("Right Side B^T A^T =\n", right_side)

Left Side (AB)^T =
 [[23 51]
 [13 29]]
Right Side B^T A^T =
 [[23 51]
 [13 29]]


In [23]:
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)
X = A_inv.dot(B)
print("Solution:", X)

Solution: [ 2.  1. -2.]


In [ ]:
import time

# ----------------------
# 1. ELEMENT-WISE ADDITION
# ----------------------

# Python lists
list1 = list(range(1_000_000))
list2 = list(range(1_000_000))

start = time.time()
list_add = [list1[i] + list2[i] for i in range(1_000_000)]
end = time.time()

print("Python List Addition Time:", end - start, "seconds")


# NumPy arrays
arr1 = np.arange(1_000_000)
arr2 = np.arange(1_000_000)

start = time.time()
arr_add = arr1 + arr2
end = time.time()

print("NumPy Addition Time:", end - start, "seconds")


# ----------------------
# 2. ELEMENT-WISE MULTIPLICATION
# ----------------------

# Python lists
start = time.time()
list_mul = [list1[i] * list2[i] for i in range(1_000_000)]
end = time.time()

print("Python List Multiplication Time:", end - start, "seconds")


# NumPy
start = time.time()
arr_mul = arr1 * arr2
end = time.time()

print("NumPy Multiplication Time:", end - start, "seconds")


# ----------------------
# 3. DOT PRODUCT
# ----------------------

# Python list dot product
start = time.time()
list_dot = sum(list1[i] * list2[i] for i in range(1_000_000))
end = time.time()

print("Python List Dot Product Time:", end - start, "seconds")


# NumPy dot product
start = time.time()
arr_dot = np.dot(arr1, arr2)
end = time.time()

print("NumPy Dot Product Time:", end - start, "seconds")


# ----------------------
# 4. MATRIX MULTIPLICATION (1000 x 1000)
# ----------------------

# Python lists
mat1 = [[i for i in range(1000)] for _ in range(1000)]
mat2 = [[i for i in range(1000)] for _ in range(1000)]

start = time.time()

# Manual matrix multiplication (slow)
result = [[sum(mat1[i][k] * mat2[k][j] for k in range(1000))
           for j in range(1000)] for i in range(1000)]

end = time.time()
print("Python List Matrix Multiplication Time:", end - start, "seconds")


# NumPy matrix multiplication
A = np.random.rand(1000, 1000)
B = np.random.rand(1000, 1000)

start = time.time()
C = np.dot(A, B)
end = time.time()

print("NumPy Matrix Multiplication Time:", end - start, "seconds")


Python List Addition Time: 0.1082620620727539 seconds
NumPy Addition Time: 0.004193782806396484 seconds
Python List Multiplication Time: 0.12238049507141113 seconds
NumPy Multiplication Time: 0.004268646240234375 seconds
Python List Dot Product Time: 0.11158943176269531 seconds
NumPy Dot Product Time: 0.0017766952514648438 seconds
